# Site
repository: https://github.com/leandro-matos/leandro-matos.github.io
favicon: images/favicon.ico

# Personal info
name: Leandro de Matos Pereira
title: Operations Analyst - Ita√∫ Unibanco
email: leandromatpereira@hotmail.com
website: https://leandro-matos.github.io/

# Social links
# twitter_username: facespics
github_username:  leandro-matos
# dribbble_username: jekyll
facebook_username: leandro.dematos.33
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: leandro-matos-pereira
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/photo.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
